name: Publish Package to npmjs
on:
  push:
    tags:
      - '*'

jobs:
  ts-publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v3
      with:
        node-version: '14.x'
        registry-url: 'https://registry.npmjs.org'
    - name: Set Release Tag Env
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - name: Set NPM Package Version
      run: make version
    - name: Install Packages
      working-directory: ./nodejs/src
      run: npm install
    - name: Build with Makefile
      run: make dist
    - name: Publish to registry
      run: npm publish --access public
      working-directory: ./nodejs
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}